apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: mreveningpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mreveningpipelinesjavascriptdocker 
    spec:
      containers:
        - name: mreveningpipelinesjavascriptdocker 
          image: testingdockerregistry.azurecr.io/mreveningpipelinesjavascriptdocker
          ports:
          - containerPort: 8080